version: '3'
services:
  elasticsearch:
    image: dungva/elasticsearch
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/var/lib/elasticsearch/data
    networks:
      - db-net

  api:
    build: .
    container_name: api-blog
    restart: on-failure
    ports:
      - 3000:3000
    links:
      - elasticsearch
    networks:
      - db-net

volumes:
  elasticsearch_data:
    driver: local

networks:
  db-net:
    driver: bridge